name = "SubstitutionTilings"
uuid = "06dea426-5f87-4913-a8ed-357464d2b34e"
authors = ["Daniel Roca González <dan.roca.6@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
